// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/api.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UniService_Status_FullMethodName       = "/proto.UniService/Status"
	UniService_StatusStream_FullMethodName = "/proto.UniService/StatusStream"
)

// UniServiceClient is the client API for UniService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UniServiceClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	StatusStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error)
}

type uniServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUniServiceClient(cc grpc.ClientConnInterface) UniServiceClient {
	return &uniServiceClient{cc}
}

func (c *uniServiceClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, UniService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uniServiceClient) StatusStream(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UniService_ServiceDesc.Streams[0], UniService_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[empty.Empty, StatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UniService_StatusStreamClient = grpc.ServerStreamingClient[StatusResponse]

// UniServiceServer is the server API for UniService service.
// All implementations must embed UnimplementedUniServiceServer
// for forward compatibility.
type UniServiceServer interface {
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	StatusStream(*empty.Empty, grpc.ServerStreamingServer[StatusResponse]) error
	mustEmbedUnimplementedUniServiceServer()
}

// UnimplementedUniServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUniServiceServer struct{}

func (UnimplementedUniServiceServer) Status(context.Context, *empty.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedUniServiceServer) StatusStream(*empty.Empty, grpc.ServerStreamingServer[StatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedUniServiceServer) mustEmbedUnimplementedUniServiceServer() {}
func (UnimplementedUniServiceServer) testEmbeddedByValue()                    {}

// UnsafeUniServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UniServiceServer will
// result in compilation errors.
type UnsafeUniServiceServer interface {
	mustEmbedUnimplementedUniServiceServer()
}

func RegisterUniServiceServer(s grpc.ServiceRegistrar, srv UniServiceServer) {
	// If the following call pancis, it indicates UnimplementedUniServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UniService_ServiceDesc, srv)
}

func _UniService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniServiceServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UniServiceServer).StatusStream(m, &grpc.GenericServerStream[empty.Empty, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UniService_StatusStreamServer = grpc.ServerStreamingServer[StatusResponse]

// UniService_ServiceDesc is the grpc.ServiceDesc for UniService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UniService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UniService",
	HandlerType: (*UniServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _UniService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _UniService_StatusStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api.proto",
}
